# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d137260ff0f9eb2a82f4539487dfb9ec"
name = "easyform"
handle = "easyform-1"
application_url = "https://chile-possibility-portable-rivers.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_metaobjects,write_metaobjects,write_metaobject_definitions,read_metaobject_definitions"

[auth]
redirect_urls = ["https://chile-possibility-portable-rivers.trycloudflare.com/auth/callback", "https://chile-possibility-portable-rivers.trycloudflare.com/auth/shopify/callback", "https://chile-possibility-portable-rivers.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
